name: Deploy to Loki


on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build FeedGen
        run: tsc

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Start Server
        run: ts-node src/index.ts
