name: Deploy to Loki


on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Get Packages
        run: npm install
      - name: Build FeedGen
        run: tsc

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Stopping Old PM2 Node Process (if there is one)
        run: |
          pm2 stop FG_Queer_Coded 2> /dev/null
          pm2 delete FG_Queer_Coded 2> /dev/null

      - name: Start PM2 Node Process
        run: pm2 start dist/index.js --name FG_Queer_Coded
