name: Deploy to Loki


on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Print CWD
        run: ls
      - name: Print Working Comands
        run: yarn run
      - name: Start yarn
        run: yar Start
