name: Deploy to Loki


on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Get Packages
        run: npm install
      - name: Build FeedGen
        run: tsc

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Start PM2 Node Process
        run: pm2 startOrGracefulReload dist/index.js --name FG_Queer_Coded
