name: Publish Feed Information

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run publishFeedGen Script
        run: ts-node scripts/publishFeedGen.ts
