name: Publish Feed Information

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Creating Local Variables
        run: |
          touch .env
          echo
      - name: Run publishFeedGen Script
        run: ts-node scripts/publishFeedGen.ts
